[workspace]
members = ["rog-core", "rog-client"]

[profile.release]
lto = true
debug = false
opt-level = 3
panic = "abort"

[profile.dev]
debug = false
opt-level = 1

[profile.bench]
lto = true
debug = false
opt-level = 3