[package]
name = "rog-core"
version = "0.1.0"
authors = ["Luke <luke@ljones.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.5"
