[workspace]
members = ["rog-core", "rog-lib"]

[profile.release]
lto = true
debug = false
opt-level = 3
#panic = "abort"

[profile.dev]
lto = true
debug = true
opt-level = 2
#panic = "abort"

[profile.bench]
lto = true
debug = false
opt-level = 3

