[workspace]
members = ["rog-core", "aura"]

[profile.release]
lto = true
debug = false
opt-level = 3
panic = "abort"

[profile.dev]
debug = false
opt-level = 2
#panic = "abort"

[profile.bench]
lto = true
debug = false
opt-level = 3
#panic = "abort"