[package]
name = "rog-core"
version = "0.3.1"
authors = ["Luke <luke@ljones.dev>"]
edition = "2018"

[dependencies]
gumdrop = "0.8"
dbus = "0.7.1"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
rog-lib = { path = "../rog-lib" }
