[package]
name = "rog-lib"
version = "0.4.0"
authors = ["Luke <luke@ljones.dev>"]
edition = "2018"

[dependencies]
rusb = "0.5"
gumdrop = "0.8"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
sysfs-class = "0.1.2"
aho-corasick = "0.7"